### ISSUE TITLE
Local Server Issue

### ISSUE THREAD

**Issue by hbatra21** [shan18/Kart#1]
While running this app on local server the images are not loaded.
What could be the reason?

**Comment by shan18** [comment]
As you can see from here
https://github.com/shan18/Kart/blob/371787017cdd8446220b646c0070c4e53065bff5/src/kart/settings/local.py#L185

the images are being served from aws S3. You would need to host these images in your aws account. I have mentioned the guidelines for setting up AWS in README.
If you want to host these images from your local computer then just comment out the line mentioned above, it should work.
